ARG ELASTIC_VERSION

# https://www.docker.elastic.co/
FROM artifactory.aecadmin.ir/ravan/kibana:${ELASTIC_VERSION}

# Add your kibana plugins setup here
# Example: RUN kibana-plugin install <name|url>
